// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortFreight.Infrastructure;

#nullable disable

namespace PortFreight.Infrastructure.Migrations
{
    [DbContext(typeof(PortFreightDatabaseContext))]
    [Migration("20260213135650_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortFreight.Domain.Entities.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("Containers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09f83d1a-0b7b-42d5-b830-f6051be5db7e"),
                            ContainerNumber = "CONT1234567",
                            ShipmentId = new Guid("e14cf002-1fae-4a03-9d9a-75f20f9631a1"),
                            Type = "40ft",
                            Weight = 12000m
                        });
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d283de6-b929-45ce-bec4-087ada6aa777"),
                            Email = "info@acme.com",
                            Name = "Acme Logistics",
                            Phone = "+44 1234 567890"
                        });
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNLocode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e423b0c-879d-4612-a690-e9bf5de4ce41"),
                            Country = "United Kingdom",
                            Name = "Port of Belfast",
                            UNLocode = "GBBEL"
                        },
                        new
                        {
                            Id = new Guid("0bb7bbe2-3bdb-4298-82f0-b921a79c1af5"),
                            Country = "Netherlands",
                            Name = "Port of Rotterdam",
                            UNLocode = "NLRTM"
                        });
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("VesselVoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationPortId");

                    b.HasIndex("OriginPortId");

                    b.HasIndex("VesselVoyageId");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e14cf002-1fae-4a03-9d9a-75f20f9631a1"),
                            CreatedAt = new DateTime(2026, 2, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("6d283de6-b929-45ce-bec4-087ada6aa777"),
                            DestinationPortId = new Guid("0bb7bbe2-3bdb-4298-82f0-b921a79c1af5"),
                            OriginPortId = new Guid("5e423b0c-879d-4612-a690-e9bf5de4ce41"),
                            ReferenceNumber = "SHIP-0001",
                            Status = 1,
                            VesselVoyageId = new Guid("f905bcbb-1101-46a9-a503-aa01212c72fb")
                        });
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapacityTEU")
                        .HasColumnType("int");

                    b.Property<string>("IMO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vessels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28de9fe0-cfbb-4dc1-bb44-23497b16c292"),
                            CapacityTEU = 12000,
                            IMO = "9876543",
                            Name = "MV Horizon"
                        });
                });

            modelBuilder.Entity("PortFreight.Domain.Events.ContainerStatusEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("ContainerStatusEvents");
                });

            modelBuilder.Entity("PortFreight.Domain.Events.TrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("TrackingEvents");
                });

            modelBuilder.Entity("PortFreight.Domain.ValueObjects.VesselVoyage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArrivalPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeparturePortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VesselId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoyageNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalPortId");

                    b.HasIndex("DeparturePortId");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselVoyages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f905bcbb-1101-46a9-a503-aa01212c72fb"),
                            ArrivalPortId = new Guid("0bb7bbe2-3bdb-4298-82f0-b921a79c1af5"),
                            ArrivalTime = new DateTime(2026, 2, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DeparturePortId = new Guid("5e423b0c-879d-4612-a690-e9bf5de4ce41"),
                            DepartureTime = new DateTime(2026, 2, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            VesselId = new Guid("28de9fe0-cfbb-4dc1-bb44-23497b16c292"),
                            VoyageNumber = "HZ123"
                        });
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Container", b =>
                {
                    b.HasOne("PortFreight.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Containers")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("PortFreight.Domain.Entities.Customer", "Customer")
                        .WithMany("Shipments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortFreight.Domain.Entities.Port", "DestinationPort")
                        .WithMany()
                        .HasForeignKey("DestinationPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortFreight.Domain.Entities.Port", "OriginPort")
                        .WithMany()
                        .HasForeignKey("OriginPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortFreight.Domain.ValueObjects.VesselVoyage", "VesselVoyage")
                        .WithMany("Shipments")
                        .HasForeignKey("VesselVoyageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DestinationPort");

                    b.Navigation("OriginPort");

                    b.Navigation("VesselVoyage");
                });

            modelBuilder.Entity("PortFreight.Domain.Events.ContainerStatusEvent", b =>
                {
                    b.HasOne("PortFreight.Domain.Entities.Container", "Container")
                        .WithMany("StatusEvents")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("PortFreight.Domain.Events.TrackingEvent", b =>
                {
                    b.HasOne("PortFreight.Domain.Entities.Shipment", "Shipment")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("PortFreight.Domain.ValueObjects.VesselVoyage", b =>
                {
                    b.HasOne("PortFreight.Domain.Entities.Port", "ArrivalPort")
                        .WithMany("ArrivingVoyages")
                        .HasForeignKey("ArrivalPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortFreight.Domain.Entities.Port", "DeparturePort")
                        .WithMany("DepartingVoyages")
                        .HasForeignKey("DeparturePortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortFreight.Domain.Entities.Vessel", "Vessel")
                        .WithMany("Voyages")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalPort");

                    b.Navigation("DeparturePort");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Container", b =>
                {
                    b.Navigation("StatusEvents");
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Port", b =>
                {
                    b.Navigation("ArrivingVoyages");

                    b.Navigation("DepartingVoyages");
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("TrackingEvents");
                });

            modelBuilder.Entity("PortFreight.Domain.Entities.Vessel", b =>
                {
                    b.Navigation("Voyages");
                });

            modelBuilder.Entity("PortFreight.Domain.ValueObjects.VesselVoyage", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
